version: "3"



services:

  jenkins:

    build:

      network: host

      context: /home/tahir/jenkins-server/jenkins-image





    volumes:

      - /jenkins-data:/var/jenkins_home

      - /var/run/docker.sock:/var/run/docker.sock



    ports:

      - "8080:8080"

      - "50000:50000"

